package hr.fer.zemris.opp.giger.config.errorHandling;

public enum ErrorCode {
    NO_SUCH_USER_EXCEPTION,
    NO_ROLE_DATA_PRESENT,
    ORGANIZER_ALREADY_EXISTS,
    BAND_NAME_NOT_UNIQUE,
    MUSICIAN_ALREADY_EXISTS,
    NO_SUCH_BAND,
    ONLY_LEADER_CAN_INVITE,
    NO_SUCH_MUSICIAN,
    NOT_INVITED,
    NOT_A_MEMBER_OF_BAND,
    ONLY_LEADER_CAN_KICK,
    ONLY_LEADER_CAN_CHANGE_LEADERSHIP,
    ONLY_MEMBER_CAN_BECOME_LEADER,
    ONLY_MEMBERS_CAN_SEE_INVITATIONS,
    ONLY_MEMBERS_CAN_EDIT_BAND
}
